steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-docker.pkg.dev/elide-fw/tools/builder", "./tools/images/builder"]
images: ["us-docker.pkg.dev/elide-fw/tools/builder"]
options:
  logging: CLOUD_LOGGING_ONLY
projectId: elide-fw
