frontend:
  - any: ["graalvm*/**/*"]
    all: ["module:graalvm"]
  - any: ["frontend/**/*"]
    all: ["module:frontend"]
  - any: ["rpc/**/*"]
    all: ["module:rpc"]
  - any: ["server/**/*"]
    all: ["module:server"]
  - any: ["base/**/*"]
    all: ["module:base"]
