## PR Size
- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 5000"
- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 1000"
- label: "PR Size"
  message: "Small"
  color: "green"
  when: "$additions < 1000"

## Draft/ready for review
- label: "Status"
  message: "Draft"
  color: "gray"
  when: "$isDraft"
- label: "Status"
  message: "Ready for review"
  color: "green"
  when: "$isDraft === false"
