steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-docker.pkg.dev/elide-fw/tools/base", "./tools/images/base"]
images: ["us-docker.pkg.dev/elide-fw/tools/base"]
options:
  logging: CLOUD_LOGGING_ONLY
projectId: elide-fw
