elide:
  assets:
    enabled: true

micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: classpath:static

grpc:
  server:
    enabled: false
