elide:
  assets:
    enabled: true

micronaut:
  caches:
    ssrContent:
      charset: 'UTF-8'
      expire-after-access: 24h
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: classpath:static

grpc:
  server:
    enabled: false
