micronaut:
  application:
    name: ssg
    default-charset: utf-8

  executors:
    type: FIXED
    default:
      threads: 1
    io:
      threads: 2
    scheduled:
      threads: 1

netty:
  default:
    allocator:
      max-order: 3
      use-cache-for-all-threads: true

jackson:
  module-scan: false
  bean-introspection-module: true
  locale: "en-US"
  serialization:
    ORDER_MAP_ENTRIES_BY_KEYS: true

grpc:
  server:
    enabled: false
