name: Site

on:
  push:
    branches:
      - stable
      - v3
      - site/*
  pull_request:
    types: [labeled, opened, reopened, synchronize]

env:
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}

jobs:
  ##
  ## Job: Site Build
  ##
  site-build:
    name: "Site: Build"
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"

    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
      - name: "Setup: QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Setup: Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Setup: GraalVM"
        uses: graalvm/setup-graalvm@v1
        with:
          components: "native-image,js"
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: "auth"
        name: "Setup: Authorize Service Account"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.BUILDBOT_SERVICE_ACCOUNT }}"
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: "Setup: Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: "Setup: Yarn"
        run: yarn
      - name: "Build: Reference Docs"
        env:
          CI: true
        run: |
          make docs reports CI=yes JVM=17
      - name: "Build: Site"
        uses: gradle/gradle-build-action@v2.3.3
        env:
          CI: true
          GRADLE_CACHE_PUSH: true
        with:
          cache-read-only: false
          arguments: |
            :site:docs:app:build
            :site:docs:app:dockerBuild
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            -Pelide.ci=true
            -Pelide.release=true
            -PbuildSamples=false
            -PbuildDocs=true
            -PbuildDocsSite=true
            -Pversions.java.language=17
            -x check
            -x apiCheck
            -x nativeTest
            -x testNativeImage
            -x nativeCompile
      - name: "Build: Compile SSG Site"
        env:
          CI: true
        run: |
          make site CI=yes JVM=17 VERBOSE=yes;
      - name: "Upload: Site Artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/site
      - name: "Post Build: Run Site"
        if: success() || failure()
        run: |
          echo "Killing docs server at PID $(cat server_pid.txt)"
          kill -9 $(cat server_pid.txt)
          rm -fv server_pid.txt

  ##
  ## Job: Site Deploy
  ##
  site-deploy:
    name: "Site: Deploy"
    runs-on: ubuntu-latest
    needs: [site-build]
    environment: github-pages
    concurrency: "deploy-pages"
    if: |
      (
        github.ref == 'refs/heads/stable' ||
        github.ref == 'refs/heads/v3' ||
        contains(github.event.pull_request.labels.*.name, 'ci:deploy-site') ||
        contains(github.event.pull_request.labels.*.name, 'ci:deploy') ||
        contains(github.event.head_commit.message, 'ci:deploy-site') ||
        contains(github.event.head_commit.message, 'ci:deploy') ||
        startsWith(github.ref, 'refs/tags/v')
      )

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"
      statuses: "write"
      deployments: "write"

    steps:
      - name: "Deploy Site: GitHub Pages"
        id: site-deploy
        uses: actions/deploy-pages@v1
