name: Site

on:
  push:
    branches:
      - stable
      - v3
      - site/*
  pull_request:
    types: [labeled, opened, reopened, synchronize]

env:
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}

jobs:
  ##
  ## Job: Site Build
  ##
  site-build:
    name: "Site: Build"
    runs-on: ubuntu-latest
    continue-on-error: false

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"

    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
      - name: "Setup: QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Setup: Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Setup: GraalVM"
        uses: graalvm/setup-graalvm@v1
        with:
          components: "native-image,js"
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: "auth"
        name: "Setup: Authorize Service Account"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.BUILDBOT_SERVICE_ACCOUNT }}"
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: "Setup: Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: "Setup: Yarn"
        run: yarn
      - name: "Build: Reference Docs"
        env:
          CI: true
        run: |
          make docs reports CI=yes JVM=17
      - name: "Build: Site"
        uses: gradle/gradle-build-action@v2.3.3
        env:
          CI: true
          GRADLE_CACHE_PUSH: true
        with:
          cache-read-only: false
          arguments: |
            :site:docs:app:build
            :site:docs:app:dockerBuild
            :site:docs:app:dockerPush
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            -Pelide.ci=true
            -Pelide.release=true
            -PbuildSamples=false
            -PbuildDocs=true
            -PbuildDocsSite=true
            -Pversions.java.language=17
            -x check
            -x apiCheck
            -x nativeTest
            -x testNativeImage
            -x nativeCompile

  ##
  ## Job: SSG Compile
  ##
  ssg-compile:
    name: "Site: SSG Compile"
    needs: [site-build]
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"

    services:
      site:
        image: us-docker.pkg.dev/elide-fw/samples/site/docs/jvm:latest
        ports:
          - 8080:8080
          - 8443:8443

    steps:
      - name: "Build: Compile SSG Site"
        env:
          CI: true
        run: |
          rm -fv ./site/docs/app/build/ssg-site.zip;
          ./gradlew \
            :packages:ssg:run \
            --warning-mode=none \
            --dependency-verification=lenient \
            -Pelide.ci=true \
            -Pelide.release=true \
            -PbuildSamples=false \
            -PbuildDocs=true \
            -PbuildDocsSite=true \
            -Pversions.java.language=17 \
            --args="--http --ignore-cert-errors --verbose --no-crawl $PWD/site/docs/app/build/generated/ksp/main/resources/elide/runtime/generated/app.manifest.pb https://localhost:8443 $PWD/site/docs/app/build/ssg-site.zip"
      - name: "Build: Assemble Site"
        run: make site CI=yes JVM=17;
      - name: "Upload: Site Artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/site

  ##
  ## Job: Site Deploy
  ##
  site-deploy:
    name: "Site: Deploy"
    runs-on: ubuntu-latest
    needs: [site-build, ssg-compile]
    environment: github-pages
    concurrency: "deploy-pages"
    if: |
      (
        github.ref == 'refs/heads/stable' ||
        github.ref == 'refs/heads/v3' ||
        contains(github.event.pull_request.labels.*.name, 'ci:deploy-site') ||
        contains(github.event.pull_request.labels.*.name, 'ci:deploy') ||
        contains(github.event.head_commit.message, 'ci:deploy-site') ||
        contains(github.event.head_commit.message, 'ci:deploy') ||
        startsWith(github.ref, 'refs/tags/v')
      )

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"
      statuses: "write"
      deployments: "write"

    steps:
      - name: "Deploy Site: GitHub Pages"
        id: site-deploy
        uses: actions/deploy-pages@v1
